#!/usr/bin/env bash

# Checks whether public_html is an empty directory
#
# Directories that contain only the standard files generated by vesta are also considered empty
#
# Returns "1" if the public_html is empty
empty() {
    local web_path="$1"

    # Checks if there is a system installed in the public directory if it exists and is not empty
    if [[ -d "$web_path/public_html" && "$(ls -A "$web_path/public_html")" ]]; then
        # List of files that are not considered to identify a system
        accepted=( 'index.html' 'robots.txt' )
        
        for file_path in "$web_path/public_html/"*; do
            file=$(basename -- "$file_path")

            invalid="1"
            for item in "${accepted[@]}"; do
                if [[ "$file" == "$item" ]]; then
                    invalid=""
                fi
            done

            # Not a permitted file for installation
            if [[ "$invalid" ]]; then
                return
            fi
        done
    fi

    echo "1"
}

check_web_dir() {
    local user_name="$1"
    local web_domain="$2"

    if [[ ! "$user_name" || ! "$web_domain" ]]; then
        echo "Invalid arguments"
        return
    fi

    web_path="/home/$user_name/web/$web_domain";

    # Check if web domain exist
    if [[ ! -d "$web_path" ]]; then
        echo "The web directory not exist."
        return
    fi

    # Check if public_html is empty
    if [[ "$(empty "$web_path")" != "1" ]]; then
        echo "The public_html is not empty."
        echo "You need delete the content manually or rename the directory to avoid data lost."
        return
    fi

    if [[ ! -d "$web_path/public_html" ]]; then
        mkdir -p "$web_path/public_html"
        chown "$user_name:$user_name" "$web_path/public_html"
    fi

    echo "1"
}

wordpress() {
    local user_name="$1"
    local web_domain="$2"

    web_path="/home/$user_name/web/$web_domain/public_html";

    rm -rf $web_path/* $web_path/.*

    cd $web_path

    su -c "wp core download" $user_name 2>&1 || return 1

    echo "Successfully downloaded Wordpress!"
}