#!/usr/bin/env bash

# Checks whether public_html is an empty directory
#
# Directories that contain only the standard files generated by vesta are also considered empty
#
# Returns "1" if the public_html is empty
empty() {
    local web_path="$1"

    # Checks if there is a system installed in the public directory if it exists and is not empty
    if [[ -d "$web_path/public_html" && "$(ls -A "$web_path/public_html")" ]]; then
        # List of files that are not considered to identify a system
        accepted=( 'index.html' 'robots.txt' )
        
        for file_path in "$web_path/public_html/"*; do
            file=$(basename -- "$file_path")

            invalid="1"
            for item in "${accepted[@]}"; do
                if [[ "$file" == "$item" ]]; then
                    invalid=""
                fi
            done

            # Not a permitted file for installation
            if [[ "$invalid" ]]; then
                return
            fi
        done
    fi

    echo "1"
}

check_web_dir() {
    local user_name="$1"
    local web_domain="$2"

    if [[ ! "$user_name" || ! "$web_domain" ]]; then
        echo "Invalid arguments"
        return
    fi

    web_path="/home/$user_name/web/$web_domain";

    # Check if web domain exist
    if [[ ! -d "$web_path" ]]; then
        echo "The web directory not exist."
        return
    fi

    # Check if public_html is empty
    if [[ "$(empty "$web_path")" != "1" ]]; then
        echo "The public_html is not empty."
        echo "You need delete the content manually or rename the directory to avoid data lost."
        return
    fi

    if [[ ! -d "$web_path/public_html" ]]; then
        mkdir -p "$web_path/public_html"
        chown "$user_name:$user_name" "$web_path/public_html"
    fi

    echo "1"
}

wordpress() {
    local user_name="$1"
    local web_domain="$2"

    web_path="/home/$user_name/web/$web_domain";

    check_dir="$(check_web_dir "$user_name" "$web_domain")"
    if [[ "$check_dir" != "1" ]]; then
        echo "$check_dir"
        return
    fi

    echo "== Downloading Wordpress..."
    curl -L -J  'https://wordpress.org/latest.zip' -o "/home/$user_name/tmp/wordpress.zip" 2>&1

    echo -e "\n== Extract files..."
    unzip "/home/$user_name/tmp/wordpress.zip" -d "/home/$user_name/tmp"
    rm -f "/home/$user_name/tmp/wordpress.zip"

    # Change owner
    chown "$user_name:$user_name" -R "/home/$user_name/tmp/wordpress"
    # Clean up vesta initial files
    rm -rf "$web_path/public_html/index.html" "$web_path/public_html/robots.txt"
    # Move files to the public_html
    mv "/home/$user_name/tmp/wordpress/"* "$web_path/public_html"
    rm -rf "/home/$user_name/tmp/wordpress"

    echo -e "\nInstallation completed"
}




